config/routes.rb
SiebelScholars::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    match "login" => "devise/sessions#new", :as => :new_user_session
  end

  get "welcome/pseudo_logout", :as => :pseudo_logout
  get "thanks" => 'welcome#thanks', :as => :thanks

  resources :nominations do
    match 'download_letter', :action => :download_letter, :conditions => { :method => :get }, :as => :download_letter
    match 'download_resume', :action => :download_resume, :conditions => { :method => :get }, :as => :download_resume
    match 'download_transcript', :action => :download_transcript, :conditions => { :method => :get }, :as => :download_transcript
    match 'download_statement', :action => :download_statement, :conditions => { :method => :get }, :as => :download_statement
    match 'download_misc', :action => :download_misc, :conditions => { :method => :get }, :as => :download_misc
  end

  root :to => "welcome#index"

  match "nomination-instructions" => 'welcome#nomination_instructions', :as => :instructions
end

app/models/nomination.rb
class Nomination < ActiveRecord::Base
  #set_primary_key :token
  cattr_reader :per_page
  @@per_page = 5
  
  extend FriendlyId
  friendly_id :nominee_name, use: :slugged
  
  attr_accessible :nominee_firstname, :nominee_lastname, :nominee_portrait, :misc_document, :nominee_statement, :nominee_resume, :nominee_transcript, :nominator_letter, :nominee_department, :nominee_ucsd_address, :nominee_ucsd_city, :nominee_ucsd_state, :nominee_ucsd_zip, :nominee_ucsd_phone, :nominee_ucsd_email, :nominee_address, :nominee_city, :nominee_state, :nominee_zip, :nominee_phone, :nominee_email
  validates_presence_of :nominee_firstname, :nominee_lastname, :nominee_department #, :nominee_ucsd_address, :nominee_ucsd_city, :nominee_ucsd_state, :nominee_ucsd_zip, :nominee_ucsd_email, :nominee_ucsd_phone, :nominee_address, :nominee_city, :nominee_state, :nominee_zip, :nominee_email, :nominee_phone

  email_name_regex  = '[\w\.%\+\-]+'
  domain_head_regex = '(?:[A-Z0-9\-]+\.)+'
  domain_tld_regex  = '(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|museum)'
  email_regex       = /\A#{email_name_regex}@#{domain_head_regex}#{domain_tld_regex}\z/i
  bad_email_message = "should look like an email address."

  %w{nominator_letter nominee_resume nominee_transcript nominee_statement misc_document}.each do |a|
    has_attached_file a, :path => ":rails_root/uploads/:class/:id/:basename.:extension"
  end
  has_attached_file :nominee_portrait, :styles => { :medium => "512x512>", :thumb => "128x128>" }
  
  belongs_to :user

  after_create :send_confirmation
  
  def nominee_name
    @name = self.nominee_firstname + " " + self.nominee_lastname
  end

  def nominator_name
    @name = self.nominator_firstname + " " + self.nominator_lastname
  end

  def send_confirmation
    NominationMailer.confirmation(self).deliver
  end

  def update_nominator
    NominationMailer.update_notificaiton(self).deliver
  end

  def complete?
    @complete = true
    @complete = false unless self.nominator_letter_file_name
    @complete = false unless self.nominee_resume_file_name
    @complete = false unless self.nominee_portrait_file_name
    @complete = false unless self.nominee_transcript_file_name
    @complete = false unless self.nominee_statement_file_name
    return @complete
  end

  def self.search(search)
    if search
      where('nominee_firstname LIKE :q OR nominee_lastname LIKE :q OR nominator_firstname LIKE :q OR nominator_lastname LIKE :q or nominee_department LIKE :q', {:q =>"%#{search}%"})
    else
      scoped
    end
  end
  
  protected
  def secure_digest(*args)
    Digest::SHA1.hexdigest(args.flatten.join('--'))
  end

  def make_token
    self.token = secure_digest(Time.now, (1..17).map{ rand.to_s })
  end
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  # This is our new function that comes before Devise's one
  before_filter :authenticate_user_from_token!
  # This is Devise's authentication
  before_filter :authenticate_user!

  helper_method :sort_column, :sort_direction
  
  def download_letter
    @nomination = Nomination.find(params[:nomination_id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
         # file = File.new(@document.document.path, "r")
         # send_data(file.read,
         #  :filename     =>  @document.document_file_name,
         #  :type         =>  @document.document_content_type,
         #  :disposition  =>  'inline') 
       
    send_file @nomination.nominator_letter.path, :type => @nomination.nominator_letter_content_type, :disposition => 'inline'
  end
  
  def download_resume
    @nomination = Nomination.find(params[:nomination_id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
    
    send_file @nomination.nominee_resume.path, :type => @nomination.nominee_resume_content_type, :disposition => 'inline'  
  end

  def download_transcript
    @nomination = Nomination.find(params[:nomination_id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
    
    send_file @nomination.nominee_transcript.path, :type => @nomination.nominee_transcript_content_type, :disposition => 'inline'    
  end


  def download_statement
    @nomination = Nomination.find(params[:nomination_id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
    
    send_file @nomination.nominee_statement.path, :type => @nomination.nominee_statement_content_type, :disposition => 'inline'    
  end

  def download_misc
    @nomination = Nomination.find(params[:nomination_id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
    
    send_file @nomination.misc_document.path, :type => @nomination.misc_document_content_type, :disposition => 'inline'    
  end
  
  # GET /nominations
  def index
    if current_user.admin
      @nominations = Nomination.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])      
    else
      @nominations = Nomination.where(:user_id => current_user).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    end
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /nominations/1
  def show
    @nomination = Nomination.find(params[:id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin
    
    if Time.now < Settings.deadline
      respond_to do |format|
        format.html { render 'errors/404', :status => 404 unless @nomination}# show.html.erb
      end
    else
      redirect_to(root_path, :notice => 'Sorry, you can no longer edit nominations') unless current_user
    end
  end

  # GET /nominations/new
  def new
    if Time.now < Settings.deadline
      @nomination = current_user.nominations.build

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @nomination }
      end
    else
      redirect_to(root_path, :notice => 'We are no longer accepting new nominations')
    end
  end

  # GET /nominations/1/edit
  def edit
    @nomination = Nomination.find(params[:id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin

    if Time.now < Settings.deadline
      redirect_to(root_path, :error => "We could not find a nomination by that token, please check the link and try again") unless @nomination
    else
      redirect_to(root_path, :notice => 'Sorry, you can no longer edit nominations') unless current_user
    end
  end

  # POST /nominations
  def create
    @nomination = current_user.nominations.create(params[:nomination])

    respond_to do |format|
      if @nomination.save
        format.html { redirect_to(thanks_url, :info => 'Nomination was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /nominations/1
  def update
    @nomination = Nomination.find(params[:id])
    @nomination = nil unless current_user.nominations.include?(@nomination) || current_user.admin

    respond_to do |format|
      if @nomination.update_attributes(params[:nomination])
        @nomination.update_nominator
        
        format.html { redirect_to(@nomination, :notice => 'Nomination was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @nomination.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nominations/1
  def destroy
    @nomination = Nomination.find(params[:id])
    @nomination.destroy if current_user.nominations.include?(@nomination) || current_user.admin

    respond_to do |format|
      format.html { redirect_to nominations_url, :notice => "Nomination was deleted." }
      format.xml  { head :ok }
    end
  end

  private
  
  def sort_column
    Nomination.column_names.include?(params[:sort]) ? params[:sort] : "nominee_lastname"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/nominations_helper.rb
module NominationsHelper

  def status_check
    if @nomination.complete?
      @html = content_tag :h4, raw("Thank you for your time, this nomination appears to have all of the required documents. You may update the data until <strong>#{Settings.deadline.strftime('%l:%M %p on %b %e')}</strong>"), :class => 'clear positive'
    else
      @html = content_tag :h4, raw("This nomination is incomplete and will not be reviewed until all required materials are included.  Please add all required info by <strong>#{Settings.deadline.strftime('%l:%M %p on %b %e')}</strong>"), :class => 'clear negative'      
    end
  end

end

app/views/nominations/_form.html.erb
<%= form_for(@nomination, :html => { :multipart => true }) do |f| %>
	<% if @nomination.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@nomination.errors.count, "error") %> prohibited this nomination from being saved:</h2>
			<ul>
				 <% @nomination.errors.full_messages.each do |msg| %>
				 	<li><%= msg %></li>
				 <% end %>
			</ul>
		</div>
	<% end %>

		<div class='padded'>
			<div>
				<h2>Nominee</h2>
				<small><strong>* denotes required fields</strong></small>
			</div>
			
			<hr />

			<div class='span-8'>
				<%= f.label :nominee_firstname, "Nominee First Name*" %><br />
				<%= f.text_field :nominee_firstname %>
			</div>
			<div class='span-8'>
				<%= f.label :nominee_lastname, "Nominee Last Name*" %><br />
				<%= f.text_field :nominee_lastname %>
			</div>
			<div class='span-8 last'>
				<%= f.label :nominee_department, "Nominee Department*" %><br />
				<%= f.text_field :nominee_department %>
			</div>
		</div>

		<hr class='padded'/>

		<div class='padded'>
			<h3>UCSD Contact Info</h3>

			<div class='span-8'>
				<%= f.label :nominee_ucsd_address, "Address*" %><br />
				<%= f.text_field :nominee_ucsd_address, size: 40 %>
			</div>
			<div class='span-4'>
				<%= f.label :nominee_ucsd_city, "City*" %><br />
				<%= f.text_field :nominee_ucsd_city, size: 18 %>
			</div>
			
			<%= f.hidden_field :nominee_ucsd_state, value: 'California' %>
			
			<div class='span-12 last'>
				<%= f.label :nominee_ucsd_zip, "Zip*" %><br />
				<%= f.text_field :nominee_ucsd_zip, size: 18 %>
			</div>

			<div class='span-8'>
				<%= f.label :nominee_ucsd_phone, "Phone*" %><br />
				<%= f.text_field :nominee_ucsd_phone %>
			</div>
			<div class='span-8 last'>
				<%= f.label :nominee_ucsd_email, "Email*" %><br />
				<%= f.text_field :nominee_ucsd_email %>
			</div>
		</div>

		<hr class='padded'/>

		<div class='padded clear'>
			<h3>Home Contact Info</h3>

			<div class='span-8'>
				<%= f.label :nominee_address, "Address*" %><br />
				<%= f.text_field :nominee_address, size: 40 %>
			</div>
			<div class='span-6'>
				<%= f.label :nominee_city, "City*" %><br />
				<%= f.text_field :nominee_city, size: 26 %>
			</div>
			
			<div class='span-6'>
				<%= f.label :nominee_state, "State*" %><br />
				<%= subregion_select(:nomination, :nominee_state, Carmen::Country.coded('US')) %>
			</div>

			<div class='span-3 last'>
				<%= f.label :nominee_zip, "Zip*" %><br />
				<%= f.text_field :nominee_zip, size: 15 %>
			</div>

			<div class='span-8'>
				<%= f.label :nominee_phone, "Phone*" %><br />
				<%= f.text_field :nominee_phone %>
			</div>
			<div class='span-8 last'>
				<%= f.label :nominee_email, "Email*" %><br />
				<%= f.text_field :nominee_email %>
			</div>
		</div>



	</div>

		<hr class='padded'/>

	<div class='clearfix'>
		<div class='span-16 border'>	
			<div class='span-8'>
				<%= f.label :nominator_letter %><br />
				<%= f.file_field :nominator_letter %>
			</div>
			<div class='span-8 last'>
				<%= f.label :nominee_resume %><br />
				<%= f.file_field :nominee_resume %>
			</div>
	
			<div class='span-8'>
				<%= f.label :nominee_transcript %><br />
				<%= f.file_field :nominee_transcript %>
			</div>
			<div class='span-8 last'>
				<%= f.label :nominee_statement %><br />
				<%= f.file_field :nominee_statement %>
			</div>
	
			<div class='span-16'>
				<%= f.label :misc_document, "Additional Document(s)"%><br /><small>*Please create a zip archive if you need to upload more than one document.</small>
				<%= f.file_field :misc_document %>
			</div>		
		</div>
		<div class='span-7 prepend-1 last'>
			<%= f.label :nominee_portrait %><br />
			<%= content_tag 'div', image_tag(@nomination.nominee_portrait.url(:thumb)), :id => 'portrait' if @nomination.nominee_portrait_file_name %>
			<%= f.file_field :nominee_portrait %>
		</div>
	</div>

	<p class='center'><em>You can save this form at any time. A confirmation email containing an update link will be sent upon any modifications to the nomination.</em></p>


	<div class='right' id="submit"><%= f.submit "Save Changes", :class => 'positive button', :onclick => "$('#nomination_submit').hide();$('#overlay').show();$('#opaque_overlay').show();$('#wait_box').show();" %></div>
<% end %>

app/views/nominations/_links.html.erb
<h3>
  <% if nomination.user == current_user %>
	  <%= link_to_unless_current 'Edit', edit_nomination_path(nomination) do link_to 'Show', nomination end %>
	<% end %>
	<%= raw(' | ' + link_to('Back', nominations_path)) if current_user %>
	
	<% if nomination.user == current_user %>
	  <%= raw(' | ' + link_to('Delete', nomination, :confirm => 'Are you sure?  This will permanently delete all data associated with this nomination.', :method => :delete)) %>
	<% end %>
</h3>

app/views/nominations/edit.html.erb
<div class='nominations'>
	<% title "Edit Nomination" %>
	<%= render 'form' %>
	<%= render 'links', :nomination => @nomination %>
</div>

app/views/nominations/index.html.erb
<% title "Nominations" %>

<%= form_tag nominations_path, :method => 'get', :id => "nominations_search" do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>&nbsp;&nbsp;&nbsp;<%= content_tag :small, link_to('Reset Search', nominations_path), :class => 'negative' if params[:sort] %></small>
	</p>
<% end %>

<table id='nominations_table'>
	<tr>
		<th colspan=2 ><%= sortable 'nominee_lastname', 'Nominee' %></th>
		<th class='department'><%= sortable 'nominee_department', 'Nominee Department' %></th>
		<th><%= sortable 'nominator_lastname', 'Nominator' %></th>
		<th><%= sortable 'created_at', 'Created' %></th>
		<th><%= sortable 'updated_at', 'Updated' %></th>
	</tr>
	<% for nomination in @nominations %>
		<tr class='nomination'>
			<td class='portrait'>
				<%= link_to image_tag(nomination.nominee_portrait.url(:thumb)), nomination_path(nomination) %><br />
				<%= link_to nomination.nominee_name, nomination_path(nomination) %>
			</td>
			<td class='links'>
				<%= content_tag :span, nomination.nominator_letter_file_name ? link_to('Nomination Letter', nomination_download_letter_url(nomination)) : raw("<strong>Nomination Letter(s)</strong> <span class='negative'>Missing</span>") %><br />
				<%= content_tag :span, nomination.nominee_resume_file_name ? link_to('Nominee Resume', nomination_download_resume_url(nomination)) : raw("<strong>Nominee Resume(s)</strong> <span class='negative'>Missing</span>")  %><br />
				<%= content_tag :span, nomination.nominee_transcript_file_name ? link_to('Nominee Transcript', nomination_download_transcript_url(nomination)) : raw("<strong>Nominee Transcript(s)</strong> <span class='negative'>Missing</span>") %><br />
				<%= content_tag :span, nomination.nominee_statement_file_name ? link_to('Nominee Statement', nomination_download_statement_url(nomination)) : raw("<strong>Nominee Statement</strong> <span class='negative'>Missing</span>")%><br />
				<%= content_tag :span, nomination.misc_document_file_name ? link_to('Extra Document(s)', nomination_download_misc_url(nomination)) : raw("<strong>No extra documents</strong>") %>
			</td>
			<td class='department'><%=link_to nomination.nominee_department.upcase, nomination %></td>
			<td>
				<%= link_to nomination.user.name, nomination_path(nomination) %><br />
				<%= mail_to nomination.user.email %>
			</td>
			<td><%= nomination.created_at.strftime "%b %e, %l:%M %p" %></td>
			<td><%= nomination.updated_at.strftime "%b %e, %l:%M %p" %></td>
		</tr>
	<% end %>
</table>

<%= will_paginate @nominations %>

<br /><br />
<h3><%= link_to "New Nomination", new_nomination_path %></h3>

app/views/nominations/new.html.erb
<div class="nomination clearfix">
	<% title "Nominate a scholar" %>
	<%= render 'form' %>
</div>

app/views/nominations/show.html.erb
<% title "Nomination" %>
<div id='nomination' class="nomination clearfix">
	<div class='span-12'>
		<h2><%=h @nomination.nominee_name %></h2>
		<p>
			<strong>Created:</strong> <%= @nomination.created_at.strftime("%b %e, %l:%M %p") %> / 
			<strong>Updated:</strong> <%= @nomination.updated_at.strftime("%b %e, %l:%M %p") %><br />
			
			<strong>Nominated by</strong> <%= @nomination.user.name %> / <%=mail_to @nomination.user.email %>
		</p>
		<p>
			<%= content_tag :span, @nomination.nominator_letter_file_name ? raw("<strong>Nomination Letter</strong> #{link_to @nomination.nominator_letter_file_name, nomination_download_letter_url(@nomination.id)}<br />") : raw("<strong>Nomination Letter(s)</strong> <span class='negative'>Missing</span><br />") %>
			<%= content_tag :span, @nomination.nominee_resume_file_name ? raw("<strong>Nominee Resume(s)</strong> #{link_to @nomination.nominee_resume_file_name, nomination_download_resume_url(@nomination.id)}<br />") : raw("<strong>Nominee Resume(s)</strong> <span class='negative'>Missing</span><br />")  %>
			<%= content_tag :span, @nomination.nominee_transcript_file_name ? raw("<strong>Nominee Transcript</strong> #{link_to @nomination.nominee_transcript_file_name, nomination_download_transcript_url(@nomination.id)}<br />") : raw("<strong>Nominee Transcript(s)</strong> <span class='negative'>Missing</span><br />") %>
			<%= content_tag :span, @nomination.nominee_statement_file_name ? raw("<strong>Nominee Statement</strong> #{link_to @nomination.nominee_statement_file_name, nomination_download_statement_url(@nomination.id)}<br />") : raw("<strong>Nominee Statement</strong> <span class='negative'>Missing</span>")%>
			<%= content_tag :span, raw("<strong>Extra Document(s)</strong> #{link_to @nomination.misc_document_file_name, nomination_download_misc_url(@nomination.id)}<br />") if @nomination.misc_document_file_name %>
		</p>
	</div>
	<div class='span-12 last' id='portrait'>
		<%= content_tag :div, image_tag(@nomination.nominee_portrait.url(:medium)) + (@nomination.nominee_portrait.url.include?('missing') ? content_tag(:h4, raw('Missing portrait'), :class => 'negative') : '' ) %>
	</div>
	<br class='clear' />
	<br class='clear' />
	<%= status_check %>
</div>
<%= content_tag :div,raw(link_to "Save Changes and Exit", pseudo_logout_url, :class => 'positive button'), :class => 'right' unless current_user %>
<%= render 'links', :nomination => @nomination %>