config/routes.rb
SiebelScholars::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    match "login" => "devise/sessions#new", :as => :new_user_session
  end

  get "welcome/pseudo_logout", :as => :pseudo_logout
  get "thanks" => 'welcome#thanks', :as => :thanks

  resources :nominations do
    match 'download_letter', :action => :download_letter, :conditions => { :method => :get }, :as => :download_letter
    match 'download_resume', :action => :download_resume, :conditions => { :method => :get }, :as => :download_resume
    match 'download_transcript', :action => :download_transcript, :conditions => { :method => :get }, :as => :download_transcript
    match 'download_statement', :action => :download_statement, :conditions => { :method => :get }, :as => :download_statement
    match 'download_misc', :action => :download_misc, :conditions => { :method => :get }, :as => :download_misc
  end

  root :to => "welcome#index"

  match "nomination-instructions" => 'welcome#nomination_instructions', :as => :instructions
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<p class='right'>
		<%= link_to image_tag('jsoe.gif'), 'http://www.jacobsschool.ucsd.edu/' %>
		<%= link_to image_tag('iem.png'), 'http://iem.ucsd.edu' %>
	</p>
	<p> 
		UC San Diego 9500 Gilman Dr. La Jolla, CA 92093 (858) 534-2230<br /> 
		Copyright &copy; <%= Time.now.year %> Regents of the University of California. All rights reserved.<br />
		<%= mail_to 'siebel@ucsd.edu', 'Feedback' %> | 
		This site is 
		<%= link_to "HTML5", "http://validator.w3.org/check?uri=https://siebel.ucsd.edu" + request.fullpath %>,
		<%= link_to "CSS3", "http://jigsaw.w3.org/css-validator/validator?uri=https://siebel.ucsd.edu" + request.fullpath + "&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en"%>, and 
		<%= link_to "Section 508", "http://www.cynthiasays.com/mynewtester/cynthia.exe?Url1=https://siebel.ucsd.edu/#{request.fullpath}&rptmode=-1&uri=https://siebel.ucsd.edu#{request.fullpath}" %> valid
	</p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<%= image_tag 'ucsd_logo.gif', :id => 'ucsd_logo' %>
	<h1><%= "#{Time.now.year + 1} Siebel Scholar Nominations".upcase %></h1>
</div>
<ul id="navbar">
	<li class='first<%= ' selected' if params[:controller] == 'welcome' && params[:action] == 'index' %>'><%= link_to "Home", root_path %></li>
	<li class='<%= ' selected' if params[:controller] == 'welcome' && params[:action] == 'nomination_instructions' %>'><%= link_to "Nomination Instructions", instructions_path %></li>
	<% unless current_user -%>
		<% if Time.now > Date.new(2014,5,30) && Time.now < Date.new(Time.now.year,6,20) %>
			<li class='<%= ' selected' if params[:controller] == 'nominations' && params[:action] == 'new' %>'><%= link_to "Nominate A Scholar", new_user_registration_path %></li>
			<li class='<%= ' selected' if params[:controller] == 'nominations' && params[:action] == 'new' %>'><%= link_to "Sign In", new_user_session_path %></li>
		<% end -%>		
	<% else  -%>
		<li class='<%= ' selected' if params[:controller] == 'nominations' && params[:action] == 'index' %>'><%= link_to "Nominations", nominations_path %></li>
		<li class='last'><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>	
	<% end -%>
</ul>
<div id="search_box">
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<meta name="description" content="Siebel Scholars 2010"/>
		<meta name="keywords" content="Siebel, Scholars"/>
	    <title>UC San Diego Siebel Scholar Nominations :: <%= (content_for?(:title) ? yield(:title) : Time.now.year + 1) %> </title>

		<%= stylesheet_link_tag "application" %>
		<!--[if lte IE 8]><%= stylesheet_link_tag "application-ie", :media => "all" %><![endif]-->
		<%= stylesheet_link_tag 'application-print', :media => "print" %>	
		
		<%= javascript_include_tag :application %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="overlay" style="display:none;"></div>
		<div id="opaque_overlay" style="display:none;">
			<div id="wait_box">
				<h2 class="padded">Please wait for the server to process your request</h2>
				<%= image_tag("progress_bar.gif") %>
			</div>
		</div>
		<div id="wrapper">
			<div class="container">
				<%= render :partial => "layouts/header" %>
				<% flash.each do |name, msg| %><%= content_tag :div, msg, :id => "flash_#{name}" if flash[name.to_sym] %><% end %>
				<div id="content"><%= yield %></div>
				<%= render :partial => "layouts/footer" %>
			</div>
		</div>
		<script type="text/javascript">
		document.write(unescape("%3Cscript src='" + (("https:" == document.location.protocol) ? "https://ssl-" : "http://")
		+ "include.reinvigorate.net/re_.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try {
		reinvigorate.track("7k7ip-w3lf8u92bv");
		} catch(err) {}
		</script>
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-19406073-3']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</body>
</html>